name = "aandjpowerwashing"
compatibility_date = "2025-09-24"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"
binding = "ASSETS"

[build]
command = "bun run build && rm dist/client/wrangler.json"